# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Starts local prometheus for metrics debugging
    cmds:
    - docker run -p 9090:9090 -v $(pwd)/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
    silent: false
